services:
  blueprint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blueprint
    ports:
      - "6342:3000"
    volumes:
      - /mnt/workspace/blueprint:/data
    restart: unless-stopped
